// snippet para obtener los recursos de tablas
// let header = document.getElementsByTagName("header")[0];
// let div = document.createElement("div");
// div.id = "content";
// div.innerHTML = '<button id="open">Open</button>';
// header.appendChild(div);
// const open = document.getElementById("open");
// open.addEventListener("click", () => {
//   const text = document
//     .getElementById("DataTables_Table_0")
//     .children[1].innerText.replaceAll("	", " - ")
//     .replaceAll("\r", "")
//     .split("\n");
//   console.log(text);
// });

export const recursos = {
  Base: { Madera: [], Cobre: [], Cuero: [], Hierro: [] },
  Materiales: {
    "Hilo de lana": [
      "Elrarangs - 19",
      "Lurtscharas - 15",
      "Skiterus - 11",
      "Mermereus - 11",
      "Kerrannas - 7",
      "Umilawens - 5",
      "Grasscrawlers - 5",
      "Doitrems - 5",
      "Elywens - 4",
      "Redos - 2",
      "Rakrests - 2",
      "Zeindras - 2",
      "Cisiens - 2",
      "Asayseths - 2",
      "Mooncruchers - 2",
      "Sugos - 2",
      "Nariths - 2",
      "Bilgs - 2",
      "Ismaels - 1",
      "Rayols - 1",
      "Uróthiens - 1",
      "Asendacs - 1",
      "Tanias - 1",
      "Calódiens - 1",
    ],
    "Bolas de algodón": [
      "de la Reversión - 10",
      "del Triunfo - 8",
      "de los Insondables - 6",
      "de la vacilación - 5",
      "de la confusión - 5",
      "de la creencia - 4",
      "del obstáculo - 4",
      "del aprendizaje - 3",
      "del Peligro - 2",
      "de la Voluntad - 1",
      "de la Invisibilidad - 1",
    ],
    Cáñamo: [
      "Tûnêsés - 16",
      "Ismaels - 13",
      "Solitanis - 13",
      "Chealoths - 11",
      "Frickoys - 11",
      "Demonkillers - 11",
      "Reinkes - 9",
      "Elywens - 8",
      "Galarands - 7",
      "Rynighte - 6",
      "Berry - 5",
      "Redo - 5",
      "Perago - 4",
      "Grank - 4",
      "Elvilmandels - 4",
      "Isundels - 4",
      "Kedyssis - 3",
      "Kosmonas - 3",
      "Tinothiel - 3",
      "Sugo - 2",
      "Cisien - 2",
      "Bacia - 2",
      "Ibiwan - 2",
      "Doitrems - 2",
      "Asayseth - 2",
      "Mima - 2",
      "Bilg - 2",
      "Mooncruchers - 2",
      "Amelia - 2",
      "Narith - 2",
      "Asendacs 2",
      "Lothay - 2",
      "Lurtschara - 1",
      "Gonak - 1",
      "Xu - 1",
      "Skiterus - 1",
      "Vuthiels - 1",
      "Watzmann - 1",
      "Mermereu - 1",
      "Ciallans - 1",
      "Zickezacke - 1",
      "Uróthien - 1",
      "Poirin - 1",
    ],
    "Tiras de gasa": [
      "de la Carne - 8",
      "de las Artes Marciale - 8",
      "de la Demolición - 7",
      "de la Distracción - 6",
      "de la Decapitación - 6",
      "de la Extirpación - 5",
      "de la Magia - 4",
      "de las Nubes - 4",
      "del obstáculo - 3",
      "del Mar - 3",
      "de la Habilidad - 3",
      "del Conflicto - 3",
      "de la Locura - 3",
      "de la Gracia - 2",
      "del Equilibrio - 2",
      "de la Prisa - 2",
      "del Peligro - 2",
      "del Bosque - 2",
      "de la confusión - 1",
      "de la Fusión - 1",
      "del insulto - 1",
    ],
    Lino: [
      "Tanias - 14",
      "Mooncruchers - 14",
      "Peragos - 14",
      "Asendacs - 14",
      "Cisiens - 13",
      "Galarands - 13",
      "Bilgs - 12",
      "Rakrests - 12",
      "Poirins - 11",
      "Berrys - 10",
      "Granks - 10",
      "Isundels - 10",
      "Grasscrawlers - 10",
      "Chalinis - 9",
      "Redos - 8",
      "Calódiens - 8",
      "Tinothiels - 7",
      "Gadriewens - 6",
      "Zeindras - 5",
      "Gonaks - 5",
      "Rynightes - 5",
      "Doitrems - 5",
      "Bacias - 4",
      "Rayols - 3",
      "Frientas - 3",
      "Ibiwans - 2",
    ],
    Yute: [
      "Xus - 12",
      "Zickezackes - 10",
      "Watzmanns - 10",
      "Frientas - 9",
      "Gadriewens - 8",
      "Kerrannas - 8",
      "Elywens - 4",
      "Asayseths - 4",
      "Mimas - 4",
      "Doitrems - 4",
      "Berrys - 4",
      "Skiterus - 3",
      "Zeindras - 2",
      "Reinkes - 2",
      "Cisiens - 2",
      "Grasscrawlers - 2",
      "Redos - 2",
      "Frabos - 2",
      "Rakrests - 2",
      "Calódiens - 1",
      "Tanias - 1",
      "Mooncruchers - 1",
      "Bilgs - 1",
      "Poirins - 1",
    ],
    "Tiras de terciopelo": [
      "de la Libertad - 13",
      "de la Presión - 11",
      "del cielo - 7",
      "de la Defensa Total - 7",
      "de la Obstrucción - 6",
      "de los Espartanos - 6",
      "del Golpe Crítico - 5",
      "de la Muerte - 4",
      "de la Prevención - 4",
      "de la Antigüedad - 2",
      "de la Benevolencia - 1",
      "de la Destrucción - 1",
    ],
    "Hilo de seda": [
      "Rynightes - 7",
      "Kosmonas - 7",
      "Chalinis - 7",
      "Zeindras - 6",
      "Mimas - 5",
      "Frientas - 5",
      "Frabos - 5",
      "Frickoys - 5",
      "Umilawens - 5",
      "Lurtscharas - 4",
      "Xus - 4",
      "Tûnêsés - 4",
      "Gadriewens - 3",
      "Chealoths - 3",
      "Zickezackes - 3",
      "Watzmanns - 3",
      "Granks - 2",
      "Ismaels - 2",
      "Vuthiels - 2",
      "Asayseths - 2",
      "Skiterus - 1",
      "Mermereus - 1",
      "Solitanis - 1",
      "Chabdyns - 1",
      "Peragos - 1",
      "Bacias - 1",
    ],
  },
  "Partes de monstruos": {
    Pelaje: [
      "del Honor - 9",
      "del Chakra - 8",
      "de la Justicia - 8",
      "de la Fusión - 7",
      "de la Magnitud - 7",
      "de la creencia - 6",
      "de los Caprichosos - 6",
      "del Brillo - 6",
      "de la Magia - 5",
      "de la Arrogancia - 5",
      "de la Generosidad - 4",
      "de la Gracia - 4",
      "de la Maldición - 4",
      "del Orgullo - 4",
      "de la Desesperación - 4",
      "de la Colina - 3",
      "de la Decapitación - 2",
      "de la Rozadura - 2",
      "de la Carne - 2",
      "de la Demolición - 2",
      "de las Artes Marciales - 2",
      "del Equilibrio - 2",
      "de la vacilación - 2",
      "de las Estrellas - 1",
      "de la Voluntad - 1",
      "del aprendizaje - 1",
      "del insulto - 1",
    ],
    "Astilla ósea": [
      "de la Brutalidad - 12",
      "de la Auto-Confianza - 10",
      "de la Fuerza - 9",
      "del Éxito - 9",
      "de la Rozadura - 9",
      "de la satisfacción - 8",
      "del Contraataque - 7",
      "del Peligro - 6",
      "de la Soltura - 6",
      "del insulto - 6",
      "de la Arrogancia - 6",
      "del Bosque - 6",
      "del Conflicto - 6",
      "de la Gloria - 6",
      "de las Montañas - 5",
      "de la Luna - 5",
      "de las Estrellas - 5",
      "de la Nostalgia - 5",
      "del Dolor - 4",
      "del Chakra - 4",
      "del aprendizaje - 4",
      "de la Generosidad - 4",
      "de la confusión - 3",
      "de los Insondables - 3",
      "de los Caprichosos - 3",
      "de la Magnitud - 2",
      "del Equilibrio - 2",
      "del Orgullo - 2",
      "de la Fusión - 1",
      "de los Benditos - 1",
      "de la Carne - 1",
      "de las Artes Marciales - 1",
    ],
    Escama: [
      "Phalangens - 24",
      "Zombers - 23",
      "Melaneos - 21",
      "Gidras - 20",
      "Heudois - 16",
      "Umfetas - 12",
      "Táliths - 5",
      "Evotavs - 5",
      "Ashitills - 4",
      "Fustriels - 3",
      "Melanchaetas - 2",
      "Uridos - 2",
      "Lulus - 1",
      "Ronaldas - 1",
    ],
    Garra: [],
    Colmillo: [
      "Beasthammers - 19",
      "Ciallans - 18",
      "Chabdyns - 18",
      "Amelias - 16",
      "Kedyssis - 15",
      "Lothays - 14",
      "Uróthiens - 13",
      "Gonaks - 13",
      "Bacias - 12",
      "Ibiwans - 12",
      "Rayols - 12",
      "Vuthiels - 10",
      "Amoviels - 10",
      "Asayseths - 9",
      "Sugos - 9",
      "Nariths - 9",
      "Demonkillers - 8",
      "Elvilmandels - 8",
      "Frabos - 7",
      "Zeindras - 6",
      "Umilawens - 5",
      "Kerrannas - 5",
      "Isundels - 4",
      "Rakrests - 4",
      "Ismaels - 2",
      "Skiterus - 2",
      "Mermereus - 2",
      "Frientas - 2",
      "Granks - 2",
      "Reinkes - 1",
      "Watzmanns - 1",
      "Poirins - 1",
      "Chalinis - 1",
      "Lurtscharas - 1",
      "Mimas - 1",
    ],
    "Escama de dragón": [
      "Dairus - 34",
      "Amulius - 34",
      "Sextus - 34",
      "Lepidus - 30",
      "Avalonio - 24",
      "Titanius - 23",
      "Tellus - 20",
      "Quinto - 16",
      "Poncio - 15",
      "Servius - 8",
      "Valerio - 6",
      "Dexterus - 5",
      "Antonius - 4",
      "Constancio - 4",
      "Aurelio - 3",
      "Gaius - 1",
      "Mandalus - 1",
    ],
    "Cuerno de toro": [
      "Chucks - 21",
      "Leandronimus - 17",
      "Sentarions - 14",
      "Barbekuus - 13",
      "Sphingens - 13",
      "Fernabasts - 12",
      "Korks - 11",
      "Tantus - 11",
      "Shivas - 10",
      "Zimbris - 7",
      "Anchorons - 6",
      "Thorstens - 6",
      "Lucius - 3",
      "Appius - 2",
      "Liloels - 2",
      "Cheggovs - 1",
      "Purmanns - 1",
    ],
    "Glándula venenosa": [
      "de la Agresión - 18",
      "de la Destrucción - 17",
      "del Golpe Crítico - 16",
      "de la Muerte - 15",
      "de Marte - 12",
    ],
    "Pelaje de Cerbero": [
      "de la Esfinge - 15",
      "de las sombras - 15",
      "de la miseria - 13",
      "de la tortura - 13",
      "de la opresión - 9",
      "de la oscuridad - 8",
      "de la transición - 8",
      "de la agonía - 7",
      "de las alas - 6",
      "del infierno - 5",
      "del calor - 5",
      "de los druidas - 2",
      "del sufrimiento - 1",
    ],
    "Escama de Hidra": [
      "Tiberius - 42",
      "Arpagius - 41",
      "Pilato - 41",
      "Minucio - 32",
      "Ambrosio - 25",
      "Porcio - 24",
      "Caesius - 24",
      "Gratio - 22",
      "Joves - 19",
      "Lete - 18",
      "Mercurialis - 14",
      "Camilo - 13",
      "Sebastiano - 13",
      "Ursus - 12",
      "Asfódelo - 10",
      "Aulo - 10",
      "Gaias - 8",
      "Valentín - 8",
      "Magno - 8",
      "Oranius - 8",
      "Angelus - 6",
      "Sergius - 2",
      "Micandriles - 2",
      "Quintas - 2",
      "Auroras - 1",
      "Primulus - 1",
      "Accas - 1",
    ],
    "Pluma de Esfinge": [
      "Mercurialis - 47",
      "Auroras - 37",
      "Aulo - 35",
      "Lete - 33",
      "Porcio - 11",
      "Dragonus - 8",
      "Oranius - 8",
      "Pilato - 6",
      "Quintas - 6",
      "Camilo - 4",
      "Primulus - 4",
      "Minucio - 3",
      "Arpagius - 3",
      "Gratio - 2",
      "Magno - 2",
      "Micandriles - 2",
      "Joves - 2",
      "Ambrosio - 1",
      "Tiberius - 1",
      "Sebastiano - 1",
      "Gaias - 1",
      "Accas - 1",
    ],
    "Piel de Tifón": [
      "Camilo - 31",
      "Dragonus - 30",
      "Oranius - 28",
      "Valentín - 28",
      "Pilato - 21",
      "Primulus - 13",
      "Ursus - 13",
      "Auroras - 9",
      "Sergius - 8",
      "Aulo - 8",
      "Sebastiano - 6",
      "Gaias - 5",
      "Caesius - 1",
      "Angelus - 1",
      "Joves - 1",
    ],
  },
  Gemas: {
    Lapislázuli: [
      "Ronaldas - 18",
      "Fustriels - 17",
      "Melanchaetas - 13",
      "Lulus - 8",
      "Evotavs - 6",
      "Medonis - 5",
      "Ashitills - 3",
      "Uridos - 3",
      "Fitschis - 3",
    ],
    Amatista: [
      "Mateus - 48",
      "Valerio - 47",
      "Marcelo - 36",
      "Servius - 31",
      "Constancio - 27",
      "Caldus - 24",
      "Giganticus - 23",
      "Gaius - 22",
      "Dexterus - 21",
      "Antonius - 18",
      "Amulius - 18",
      "Lepidus - 15",
      "Titanius - 14",
      "Belesario - 13",
      "Poncio - 13",
      "Tellus - 12",
      "Sextus - 12",
      "Avalonio - 10",
      "Quinto - 8",
      "Dairus - 1",
    ],
    Ámbar: [
      "del Conocimiento - 17",
      "del Bautismo - 17",
      "de la Concentración - 16",
      "de la Recuperación - 16",
      "de la Superioridad Espiritual - 15",
      "de la Vida - 15",
      "del Relámpago Fantasmal - 14",
      "de la Virtuosidad - 14",
      "de la Inteligencia - 12",
      "de la paz - 12",
      "del regreso - 12",
      "de la Pureza - 11",
      "del Sacramento - 11",
      "de la Pandemia - 10",
      "del Matrimonio - 9",
      "de la Salud - 9",
      "de la firmeza - 7",
      "de la Expansión - 6",
      "de la Resolución - 5",
      "de los Ingresos - 4",
      "de la Ilusión - 4",
      "de la Armonía - 4",
      "de la independencia - 3",
      "del disturbio - 3",
      "de la delicadeza - 3",
      "de la Gracia - 3",
      "del Sol - 2",
      "del Terror - 2",
      "de la Victima - 2",
      "de la seguridad - 2",
      "de la Fragmentación - 2",
      "de la magnificencia - 2",
      "de la Masculinidad - 2",
      "de la Corrosión - 1",
      "del Coraje - 1",
      "del Desfile - 1",
      "de la Diligencia - 1",
      "de los Malditos - 1",
      "de la Evasión - 1",
      "del veneno - 1",
      "de la Protección - 1",
      "de la Fragmentación - 1",
    ],
    Aguamarina: [
      "de la Luz - 13",
      "de la Diligencia - 11",
      "del Sol - 11",
      "del Coraje - 11",
      "de la Espátula - 10",
      "de los Ingresos - 9",
      "del Amazonas - 9",
      "de la Armonía - 8",
      "del Sufrimiento - 7",
      "de los Muertos Vivientes - 5",
      "de la magnificencia - 4",
      "de la Pureza - 4",
      "del Desfile - 4",
      "de la Victima - 4",
      "de la Evasión - 3",
      "de la Ilusión - 3",
      "de la Fragmentación - 2",
      "de la Masculinidad - 1",
      "de los Malditos - 1",
      "del disturbio - 1",
      "de la Gracia - 1",
    ],
    Zafiro: [
      "de la Religiosidad - 12",
      "de la Ceremonia - 11",
      "de la Ordenanza - 10",
      "de la Emasculación - 10",
      "del Luto - 9",
      "de la Consagración - 9",
      "de la Espiritualidad - 9",
      "de los Benditos - 9",
      "de la Curación - 8",
      "de la Curiosidad - 7",
      "de la Normalidad - 7",
      "de la Heridas - 7",
      "de la Invisibilidad - 7",
      "de la Liturgia - 6",
      "de la Desesperación - 6",
      "de las Montañas - 5",
      "de la Colina - 5",
      "de la Maldición - 5",
      "de la Lluvia - 4",
      "de las Nubes - 4",
      "de la Sangre - 4",
      "de la Luna - 3",
      "de la Locura - 3",
      "del Miedo - 3",
      "de la Presteza - 2",
      "del Orgullo - 2",
      "de la Justicia - 2",
      "del Mar - 2",
      "del Equilibrio - 2",
      "de la Generosidad - 2",
      "de la Carne - 1",
      "de la Demolición - 1",
      "del Honor - 1",
      "de la confusión - 1",
      "del insulto - 1",
      "de la creencia - 1",
      "de la satisfacción - 1",
      "del aprendizaje - 1",
    ],
    Granate: [
      "Marcus - 48",
      "Shivas - 35",
      "Purmanns - 32",
      "Liloels - 31",
      "Stoybaers - 29",
      "Anchorons - 20",
      "Jennifers - 13",
      "Opiehnzas - 8",
      "Barbekuus - 6",
      "Ichorus - 5",
      "Trafans - 4",
      "Cheggovs - 3",
      "Fernabasts - 1",
      "Sentarions - 1",
      "Korks - 1",
      "Lucius - 1",
    ],
    Esmeralda: [
      "Aurelio - 56",
      "Virgilio - 56",
      "Silvano - 54",
      "Spurius - 52",
      "Mandalus - 52",
      "Caldus - 23",
      "Dexterus - 14",
      "Giganticus - 10",
      "Constancio - 6",
      "Servius - 4",
      "Manius - 4",
      "Avalonio - 4",
      "Belesario - 4",
      "Dairus - 3",
      "Marcelo - 3",
      "Lepidus - 3",
      "Titus - 3",
      "Quinto - 2",
      "Titanius - 2",
      "Mateus - 2",
      "Sextus - 1",
    ],
    Diamante: [
      "de los Campos Elíseos - 18",
      "de la Rivalidad - 11",
      "de la Ligereza - 9",
      "de la Maldición - 9",
      "de la soledad - 9",
      "del Infierno - 8",
      "de la Tierra - 3",
      "de la Promesa - 3",
    ],
    Jaspe: [
      "del desfiladero - 46",
      "del espíritu - 27",
      "de la tortura - 22",
      "del sueño - 20",
      "de la bestia - 13",
      "de las fatigas - 13",
      "de la miseria - 13",
      "de la tristeza - 10",
      "de los demonios - 10",
      "de la extenuación - 10",
      "de la confianza - 8",
      "de la serpiente - 7",
      "del alma - 7",
      "de la opresión - 6",
      "de las tinieblas - 5",
      "de la decadencia - 5",
      "del peligro - 4",
      "del juez - 4",
      "del sufrimiento - 3",
      "de las profundidades - 2",
      "de la divinidad - 2",
      "del calor - 2",
      "de las alas - 1",
      "de los druidas - 1",
    ],
    Sugilita: [
      "Africanus - 58",
      "Gratias - 47",
      "Angelus - 47",
      "Magno - 44",
      "Caesius - 44",
      "Joves - 40",
      "Asfódelo - 39",
      "Quintas - 35",
      "Ambrosio - 26",
      "Porcio - 24",
      "Sergius - 24",
      "Auroras - 22",
      "Valentín - 21",
      "Aulo - 18",
      "Sebastiano - 14",
      "Micandriles - 12",
      "Minucio - 9",
      "Gaias - 8",
      "Accas - 8",
      "Dragonus - 6",
      "Primulus - 5",
      "Lete - 5",
      "Oranius - 4",
      "Arpagius - 4",
      "Mercurialis - 3",
      "Gratio - 2",
      "Tiberius - 2",
      "Ursus - 2",
    ],
  },
  Frascos: {
    "Veneno de escorpión": [
      "del Odio - 15",
      "del misterio - 13",
      "de la Venganza - 12",
      "de la Batalla - 12",
      "de la Resolución - 12",
      "del poder - 11",
      "del aprendizaje - 11",
      "de la Fragmentación - 10",
      "del veneno - 10",
      "de la Expansión - 9",
      "del Estímulo - 9",
      "del Amazonas - 9",
      "del Asesinato - 9",
      "de la pasión - 7",
      "de la Victima - 7",
      "del Matrimonio - 7",
      "de la Masculinidad - 7",
      "de la Espátula - 6",
      "del disturbio - 6",
      "de la Violencia - 6",
      "del Funámbulo - 5",
      "de la Perdición - 4",
      "del Terror - 4",
      "del Sacramento - 2",
      "de los Ingresos - 1",
      "de la Fragmentación - 1",
      "de la Corrosión - 1",
      "de la delicadeza - 1",
      "de la firmeza - 1",
      "del Homunculus - 1",
      "del Desfile - 1",
    ],
    "Tintura de la resistencia": [
      "Lucius - 27",
      "Sentarions - 24",
      "Tantus - 21",
      "Fernabasts - 21",
      "Korks - 20",
      "Leandronimus - 13",
      "Decimus - 10",
      "Stoybaers - 10",
      "Barbekuus - 10",
      "Anchorons - 9",
      "Appius - 7",
      "Trafans - 6",
      "Ichorus - 5",
      "Opiehnzas - 2",
    ],
    Antídoto: [
      "del Homunculus - 16",
      "del Sacrificio - 16",
      "de la Ignorancia - 15",
      "del Sentimentalismo - 14",
      "de la Auto-Disciplina - 14",
      "de la Protección - 14",
      "de los Malditos - 12",
      "de los Momentos - 12",
      "de la seguridad - 11",
      "de la Retirada - 11",
      "del Funámbulo - 8",
      "de la Gracia - 7",
      "de la independencia - 7",
      "del Terror - 6",
      "de la Violencia - 6",
      "de la magnificencia - 6",
      "del disturbio - 5",
      "de la pasión - 5",
      "del Estímulo - 4",
      "de la firmeza - 4",
      "de la Salud - 3",
      "del poder - 1",
    ],
    Adrenalina: [
      "Bereccas - 22",
      "Medonis - 22",
      "Fitschis - 20",
      "Heuhois - 19",
      "Evotavs - 10",
      "Umfetas - 9",
      "Uridos - 5",
      "Ashitills - 4",
      "Gidras - 2",
      "Heudois - 2",
      "Ronaldas - 1",
      "Lulus - 1",
      "Melaneos - 1",
    ],
    "Tintura de la inspiración": [
      "de la Ingeniosidad - 23",
      "de la Benevolencia - 21",
      "de la Necedad - 21",
      "de la Consideración - 21",
      "de la Recuperación - 20",
      "de la Resistencia - 20",
      "del Aleluya - 20",
      "de Orión - 19",
      "del Rigor Mortis - 19",
      "de la Regeneración - 19",
      "de la Denominación - 15",
      "de la Hipocresía - 13",
      "de la Piedad - 9",
      "de la Vocación - 8",
      "de la Defensa Total - 2",
      "del cielo - 2",
      "de la Muerte - 2",
      "de la Agresión - 2",
      "del Golpe Crítico - 2",
      "de la Herida de Carne - 1",
      "de la Obstrucción - 1",
    ],
    "Poción de la percepción": [
      "Zimbris - 34",
      "Thorstens - 33",
      "Cheggovs - 30",
      "Lucius - 12",
      "Sphingens - 12",
      "Appius - 9",
      "Decimus - 7",
      "Ichorus - 2",
      "Opiehnzas - 2",
      "Stoybaers - 1",
    ],
    "Esencia de los reflejos": [
      "de la Promesa - 22",
      "de la Tierra - 17",
      "de la Dominancia - 13",
      "de la Marginalidad - 6",
      "de la Ligereza - 5",
      "del Dragón - 4",
      "de los Campos Elíseos - 2",
      "de la plaga - 2",
      "de la Locura - 1",
      "de la Verdad - 1",
      "del Fuego - 1",
    ],
    "Frasco de carisma": [
      "de la plaga - 27",
      "de los Campos Elíseos - 7",
      "de la Rivalidad - 5",
      "de la Tierra - 4",
      "de la Maldición - 4",
      "de la Esperanza - 4",
      "de la Dominancia - 2",
      "del Dragón - 1",
      "de la Promesa - 1",
      "del Fuego - 1",
    ],
    "Agua del olvido": [
      "de los druidas - 38",
      "del fuego infernal - 38",
      "de Tártaro - 33",
      "del terror - 32",
      "del grito - 32",
      "del horror - 31",
      "de la destrucción - 30",
      "de la divinidad - 29",
      "del frío - 28",
      "de la confianza - 27",
      "de la decadencia - 26",
      "de la transición - 25",
      "de la agonía - 22",
      "del juez - 22",
      "del calor - 21",
      "de las profundidades - 20",
      "del infierno - 19",
      "de lo desconocido - 16",
      "del sufrimiento - 16",
      "de la serpiente - 16",
      "del tormento - 15",
      "del fantasma - 15",
      "del Aqueronte - 14",
      "de la Hidra - 13",
      "de la extenuación - 10",
      "del tormento - 9",
      "de las fatigas - 8",
      "de la bestia - 8",
      "de las sombras - 7",
      "de los demonios - 6",
      "de la aparición - 5",
      "de las tinieblas - 4",
      "de la huida - 4",
      "de Mercurio - 3",
      "de la indecisión - 2",
      "de la oscuridad - 2",
      "del desfiladero - 1",
    ],
    "Esencia de alma": [
      "Accas - 73",
      "Gaias - 55",
      "Quintas - 45",
      "Gratias - 19",
      "Arpagius - 18",
      "Minucio - 15",
      "Camilo - 12",
      "Oranius - 9",
      "Ambrosio - 8",
      "Tiberius - 8",
      "Dragonus - 8",
      "Valentín - 6",
      "Asfódelo - 5",
      "Joves - 4",
      "Primulus - 4",
      "Magno - 4",
      "Angelus - 3",
      "Gratio - 3",
      "Ursus - 2",
      "Sebastiano - 2",
      "Auroras - 1",
    ],
  },
  Runas: {
    "Sello acuático": [
      "Lulus - 9",
      "Ronaldas - 7",
      "Fustriels - 7",
      "Melanchaetas - 6",
      "Melaneos - 5",
      "Gidras - 5",
      "Zombers - 5",
      "Heudois - 3",
      "Umfetas - 2",
      "Adendathiels - 1",
    ],
    "Runa protectora": [
      "de la Exactitud - 20",
      "del cielo - 12",
      "de la Enfermedad - 12",
      "de los Espartanos - 1",
      "de la Defensa Total - 1",
    ],
    "Grabado terrestre": [
      "de la Prisa - 10",
      "de la Nostalgia - 7",
      "de la Rapidez - 7",
      "del Dolor - 6",
      "de la Voluntad - 5",
      "de la Distracción - 5",
      "de la Lluvia - 4",
      "de la Presteza - 4",
      "de la Locura - 4",
      "de la Sangre - 4",
      "del obstáculo - 3",
      "de la Habilidad - 3",
      "de la Luna - 3",
      "del Miedo - 3",
      "del Mar - 2",
      "de la vacilación - 2",
      "del Equilibrio - 2",
      "de la Extirpación - 2",
      "del Bosque - 1",
      "del Conflicto - 1",
      "de la Fusión - 1",
    ],
    "Tótem curativo": [
      "del Amor - 30",
      "de la Verdad - 27",
      "de la soledad - 24",
      "de la Locura - 23",
      "de la Marginalidad - 7",
      "de la plaga - 6",
      "de la Esperanza - 4",
      "de los Campos Elíseos - 4",
      "de la Maldición - 3",
      "de la Rivalidad - 2",
      "del Infierno - 2",
      "de la Fuerza - 1",
      "de la Promesa - 1",
      "de la Dominancia - 1",
      "de la Tierra - 1",
    ],
    "Talismán de poder": [
      "de la malicia - 20",
      "de la Antigüedad - 13",
      "de la Vocación - 11",
      "de la Piedad - 9",
      "de la Enfermedad - 9",
      "de la Presión - 9",
      "de la Libertad - 9",
      "de Marte - 7",
      "de la Hipocresía - 6",
      "de la Denominación - 3",
      "de la Destrucción - 2",
      "de la Prevención - 2",
      "de los Espartanos - 2",
      "de la Obstrucción - 1",
      "de la Defensa Total - 1",
      "de la Herida de Carne - 1",
      "de la Muerte - 1",
      "de la Regeneración - 1",
      "de la Agresión - 1",
      "del Golpe Crítico - 1",
    ],
    "Piedra de la suerte": [
      "del silencio - 12",
      "de la Fragmentación - 11",
      "de los Muertos Vivientes - 4",
      "de la delicadeza - 4",
      "de la pasión - 3",
      "de la Ilusión - 2",
      "de la Masculinidad - 2",
      "de la independencia - 1",
      "del veneno - 1",
      "del aprendizaje - 1",
      "del Asesinato - 1",
    ],
    Pedernal: [
      "Táliths - 22",
      "Orlelds - 21",
      "Adendathiels - 20",
      "Uridos - 15",
      "Ashitills - 13",
      "Heuhois - 10",
      "Evotavs - 9",
      "Lulus - 5",
      "Melaneos - 3",
      "Zombers - 3",
      "Bereccas - 1",
      "Fitschis - 1",
      "Umfetas - 1",
      "Ronaldas - 1",
      "Gidras - 1",
      "Fustriels - 1",
      "Melanchaetas - 1",
    ],
    "Runa de la tormenta": [
      "Umbros - 40",
      "Chucks - 23",
      "Xenphlames - 21",
      "Opiehnzas - 18",
      "Appius - 17",
      "Sentarions - 7",
      "Trafans - 6",
      "Tantus - 4",
      "Lucius - 4",
      "Korks - 3",
      "Fernabasts - 1",
    ],
    "Runa de las sombras": [
      "de las alas - 27",
      "de la noche - 27",
      "del peligro - 26",
      "de la indecisión - 23",
      "del tormento - 20",
      "de la piedra - 17",
      "de la tristeza - 13",
      "del sufrimiento - 12",
      "del sueño - 11",
      "del juez - 6",
      "de la Esfinge - 4",
      "de la decadencia - 4",
      "de los druidas - 4",
      "del horror - 3",
      "de la oscuridad - 2",
    ],
  },
  Minerales: {
    Cristal: [
      "Manius - 42",
      "Gaius - 31",
      "Belesario - 30",
      "Antonius - 30",
      "Titus - 29",
      "Quinto - 25",
      "Poncio - 22",
      "Tellus - 19",
      "Marcelo - 17",
      "Titanius - 17",
      "Servius - 8",
      "Dexterus - 6",
      "Valerio - 6",
      "Constancio - 4",
      "Amulius - 2",
    ],
    Bronce: [
      "de la Revancha - 22",
      "del Dragón - 20",
      "de la Esperanza - 18",
      "del Infierno - 14",
      "de la Rivalidad - 11",
      "de la Maldición - 11",
      "de la Marginalidad - 7",
      "de la Ligereza - 6",
      "de la Tierra - 4",
      "de la Dominancia - 4",
      "de la Fuerza - 3",
      "del Fuego - 3",
      "de la Promesa - 2",
    ],
    Obsidiana: [
      "Avalonio - 13",
      "Dairus - 12",
      "Constancio - 12",
      "Caldus - 11",
      "Giganticus - 11",
      "Belesario - 8",
      "Titus - 8",
      "Poncio - 7",
      "Lepidus - 5",
      "Quinto - 4",
      "Sextus - 4",
      "Tellus - 1",
    ],
    Plata: [
      "de la Corrosión - 12",
      "de la Evasión - 10",
      "del Sufrimiento - 9",
      "del Desfile - 8",
      "de la Perdición - 8",
      "de la delicadeza - 5",
      "de los Muertos Vivientes - 5",
      "de la Ilusión - 3",
      "de la Pandemia - 3",
      "de la Espátula - 2",
      "de la Fragmentación - 2",
      "del Asesinato - 1",
      "de la Retirada - 1",
      "de la independencia - 1",
      "de la Expansión - 1",
    ],
    Azufre: [
      "Ichorus - 35",
      "Decimus - 32",
      "Jennifers - 29",
      "Trafans - 19",
      "Appius - 13",
      "Opiehnzas - 12",
      "Xenphlames - 12",
      "Tantus - 12",
      "Anchorons - 12",
      "Leandronimus - 11",
      "Barbekuus - 9",
      "Sphingens - 9",
      "Thorstens - 4",
      "Zimbris - 4",
      "Fernabasts - 4",
      "Cheggovs - 3",
      "Purmanns - 3",
      "Lucius - 2",
      "Stoybaers - 1",
    ],
    "Mena de oro": [
      "Titus - 12",
      "Giganticus - 10",
      "Amulius - 8",
      "Caldus - 7",
      "Avalonio - 7",
      "Dexterus - 6",
      "Constancio - 4",
      "Manius - 4",
      "Tellus - 3",
      "Antonius - 3",
      "Lepidus - 3",
      "Titanius - 2",
      "Poncio - 1",
      "Sextus - 1",
    ],
    Cuarzo: [
      "de la Fuerza - 23",
      "del Fuego - 19",
      "de la Marginalidad - 7",
      "de la Ligereza - 6",
      "de la Dominancia - 6",
      "del Dragón - 4",
      "de la Revancha - 2",
      "de la Promesa - 1",
    ],
    Platino: [
      "de la Herida de Carne - 19",
      "de la Obstrucción - 16",
      "de los Espartanos - 14",
      "de la Defensa Total - 14",
      "de la Prevención - 13",
      "de la Antigüedad - 3",
      "de la Presión - 1",
      "de la Libertad - 1",
    ],
    Almandino: [
      "Escribonio - 70",
      "Micandriles - 45",
      "Gratio - 37",
      "Primulus - 37",
      "Ursus - 33",
      "Sergius - 31",
      "Sebastiano - 24",
      "Africanus - 12",
      "Porcio - 11",
      "Angelus - 10",
      "Camilo - 8",
      "Dragonus - 8",
      "Tiberius - 8",
      "Asfódelo - 6",
      "Magno - 6",
      "Minucio - 5",
      "Oranius - 5",
      "Gratias - 3",
      "Ambrosio - 2",
      "Lete - 2",
    ],
    Cuprita: [
      "del abismo - 34",
      "de Mercurio - 27",
      "de la piedra - 16",
      "de la huida - 11",
      "del Aqueronte - 10",
      "de los demonios - 9",
      "de la confianza - 6",
      "del espíritu - 5",
      "de la divinidad - 4",
      "de la oscuridad - 4",
      "del sueño - 3",
      "de la agonía - 2",
      "de las profundidades - 1",
    ],
    "Piedra infernal": [
      "de Cerbero - 33",
      "de la aparición - 29",
      "del alma - 26",
      "del tormento - 25",
      "de las tinieblas - 22",
      "de la opresión - 20",
      "de la Hidra - 20",
      "de la huida - 19",
      "de lo desconocido - 17",
      "del fantasma - 17",
      "de la Esfinge - 16",
      "de la oscuridad - 15",
      "de la extenuación - 14",
      "de las fatigas - 13",
      "de las profundidades - 11",
      "de las sombras - 11",
      "de la bestia - 11",
      "del infierno - 10",
      "de la serpiente - 10",
      "de la tristeza - 8",
      "del Aqueronte - 8",
      "de los demonios - 8",
      "del peligro - 5",
      "de la indecisión - 5",
      "de la noche - 5",
      "de la destrucción - 4",
      "de la miseria - 4",
      "de Mercurio - 3",
      "del calor - 3",
      "de la agonía - 3",
      "del terror - 2",
      "del frío - 2",
      "del sufrimiento - 1",
      "del juez - 1",
    ],
  },
};
