export const recursos = {
  Base: { Madera: [], Cobre: [], Cuero: [], Hierro: [] },
  Materiales: {
    "Hilo de lana": [
      "Elrarangs - 19",
      "Lurtscharas - 15",
      "Skiterus - 11",
      "Mermereus - 11",
      "Kerrannas - 7",
      "Umilawens - 5",
      "Grasscrawlers - 5",
      "Doitrems - 5",
      "Elywens - 4",
      "Redos - 2",
      "Rakrests - 2",
      "Zeindras - 2",
      "Cisiens - 2",
      "Asayseths - 2",
      "Mooncruchers - 2",
      "Sugos - 2",
      "Nariths - 2",
      "Bilgs - 2",
      "Ismaels - 1",
      "Rayols - 1",
      "Uróthiens - 1",
      "Asendacs - 1",
      "Tanias - 1",
      "Calódiens - 1",
    ],
    "Bolas de algodón": [
      "de la Reversión - 10",
      "del Triunfo - 8",
      "de los Insondables - 6",
      "de la vacilación - 5",
      "de la confusión - 5",
      "de la creencia - 4",
      "del obstáculo - 4",
      "del aprendizaje - 3",
      "del Peligro - 2",
      "de la Voluntad - 1",
      "de la Invisibilidad - 1",
    ],
    Cáñamo: [
      "Tûnêsés - 16",
      "Ismaels - 13",
      "Solitanis - 13",
      "Chealoths - 11",
      "Frickoys - 11",
      "Demonkillers - 11",
      "Reinkes - 9",
      "Elywens - 8",
      "Galarands - 7",
      "Rynighte - 6",
      "Berry - 5",
      "Redo - 5",
      "Perago - 4",
      "Grank - 4",
      "Elvilmandels - 4",
      "Isundels - 4",
      "Kedyssis - 3",
      "Kosmonas - 3",
      "Tinothiel - 3",
      "Sugo - 2",
      "Cisien - 2",
      "Bacia - 2",
      "Ibiwan - 2",
      "Doitrems - 2",
      "Asayseth - 2",
      "Mima - 2",
      "Bilg - 2",
      "Mooncruchers - 2",
      "Amelia - 2",
      "Narith - 2",
      "Asendacs 2",
      "Lothay - 2",
      "Lurtschara - 1",
      "Gonak - 1",
      "Xu - 1",
      "Skiterus - 1",
      "Vuthiels - 1",
      "Watzmann - 1",
      "Mermereu - 1",
      "Ciallans - 1",
      "Zickezacke - 1",
      "Uróthien - 1",
      "Poirin - 1",
    ],
    "Tiras de gasa": [
      "de la Carne - 8",
      "de las Artes Marciale - 8",
      "de la Demolición - 7",
      "de la Distracción - 6",
      "de la Decapitación - 6",
      "de la Extirpación - 5",
      "de la Magia - 4",
      "de las Nubes - 4",
      "del obstáculo - 3",
      "del Mar - 3",
      "de la Habilidad - 3",
      "del Conflicto - 3",
      "de la Locura - 3",
      "de la Gracia - 2",
      "del Equilibrio - 2",
      "de la Prisa - 2",
      "del Peligro - 2",
      "del Bosque - 2",
      "de la confusión - 1",
      "de la Fusión - 1",
      "del insulto - 1",
    ],
    Lino: [
      "Tania - 14",
      "Mooncruchers 14",
      "Perago - 14",
      "Asendacs 14",
      "Cisien - 13",
      "Galarand - 13",
      "Bilg - 12",
      "Rakrests 12",
      "Poirin - 11",
      "Berry - 10",
      "Grank - 10",
      "Isundels 10",
      "Grasscrawler - 10",
      "Chalinis 9",
      "Redo - 8",
      "Calódien - 8",
      "Tinothiel - 7",
      "Gadriewen - 6",
      "Zeindras 5",
      "Gonak - 5",
      "Rynighte - 5",
      "Doitrems 5",
      "Bacia - 4",
      "Rayol - 3",
      "Frientas 3",
      "Ibiwan - 2",
    ],
    Yute: [
      "Xus - 12",
      "Zickezacke - 10",
      "Watzmann - 10",
      "Frienta - 9",
      "Gadriewens 8",
      "Kerranna - 8",
      "Elywen - 4",
      "Asayseth - 4",
      "Mima - 4",
      "Doitrem - 4",
      "Berrys 4",
      "Skiteru - 3",
      "Zeindra - 2",
      "Reinke - 2",
      "Cisien - 2",
      "Grasscrawler - 2",
      "Redo - 2",
      "Frabos 2",
      "Rakrest - 2",
      "Calódien - 1",
      "Tanias - 1",
      "Mooncrucher - 1",
      "Bilg - 1",
      "Poirin - 1",
    ],
    "Tiras de terciopelo": [
      "de la Libertad - 13",
      "de la Presión - 11",
      "del cielo - 7",
      "de la Defensa Total - 7",
      "de la Obstrucción - 6",
      "de los Espartano - 6",
      "del Golpe Crítico - 5",
      "de la Muerte - 4",
      "de la Prevención - 4",
      "de la Antigüedad - 2",
      "de la Benevolencia - 1",
      "de la Destrucción - 1",
    ],
    "Hilo de seda": [
      "Rynightes - 7",
      "Kosmona - 7",
      "Chalini - 7",
      "Zeindra - 6",
      "Mima - 5",
      "Frienta - 5",
      "Frabos - 5",
      "Frickoy - 5",
      "Umilawen - 5",
      "Lurtschara - 4",
      "Xu - 4",
      "Tûnêsé - 4",
      "Gadriewens 3",
      "Chealoth - 3",
      "Zickezacke - 3",
      "Watzmann - 3",
      "Granks - 2",
      "Ismael - 2",
      "Vuthiel - 2",
      "Asayseth - 2",
      "Skiteru - 1",
      "Mermereu - 1",
      "Solitani - 1",
      "Chabdyn - 1",
      "Perago - 1",
      "Bacias - 1",
    ],
  },
  "Partes de monstruos": {
    Pelaje: [
      "del Honor - 9",
      "del Chakra - 8",
      "de la Justicia - 8",
      "de la Fusión - 7",
      "de la Magnitud - 7",
      "de la creencia - 6",
      "de los Caprichosos - 6",
      "del Brillo - 6",
      "de la Magia - 5",
      "de la Arrogancia - 5",
      "de la Generosidad - 4",
      "de la Gracia - 4",
      "de la Maldición - 4",
      "del Orgullo - 4",
      "de la Desesperación - 4",
      "de la Colina - 3",
      "de la Decapitación - 2",
      "de la Rozadura - 2",
      "de la Carne - 2",
      "de la Demolición - 2",
      "de las Artes Marciales - 2",
      "del Equilibrio - 2",
      "de la vacilación - 2",
      "de las Estrella - 1",
      "de la Voluntad - 1",
      "del aprendizaje - 1",
      "del insulto - 1",
    ],
    "Astilla ósea": [
      "de la Brutalidad - 12",
      "de la Auto-Confianza - 10",
      "de la Fuerza - 9",
      "del Éxito - 9",
      "de la Rozadura - 9",
      "de la satisfacción - 8",
      "del Contraataque - 7",
      "del Peligro - 6",
      "de la Soltura - 6",
      "del insulto - 6",
      "de la Arrogancia - 6",
      "del Bosque - 6",
      "del Conflicto - 6",
      "de la Gloria - 6",
      "de las Montaña - 5",
      "de la Luna - 5",
      "de las Estrella - 5",
      "de la Nostalgia - 5",
      "del Dolor - 4",
      "del Chakra 4",
      "del aprendizaje - 4",
      "de la Generosidad - 4",
      "de la confusión - 3",
      "de los Insondables - 3",
      "de los Caprichosos - 3",
      "de la Magnitud - 2",
      "del Equilibrio - 2",
      "del Orgullo - 2",
      "de la Fusión - 1",
      "de los Bendito - 1",
      "de la Carne - 1",
      "de las Artes Marciales - 1",
    ],
    Escama: [
      "Phalangen - 24",
      "Zomber - 23",
      "Melaneo - 21",
      "Gidras 20",
      "Heudoi - 16",
      "Umfeta - 12",
      "Tálith - 5",
      "Evotav - 5",
      "Ashitill - 4",
      "Fustriel - 3",
      "Melanchaeta - 2",
      "Uridos - 2",
      "Lulu - 1",
      "Ronalda - 1",
    ],
    Garra: [],
    Colmillo: [
      "Beasthammer - 19",
      "Ciallan - 18",
      "Chabdyn - 18",
      "Amelia - 16",
      "Kedyssi - 15",
      "Lothay - 14",
      "Uróthien - 13",
      "Gonaks - 13",
      "Bacias - 12",
      "Ibiwan - 12",
      "Rayols - 12",
      "Vuthiel - 10",
      "Amoviel - 10",
      "Asayseth - 9",
      "Sugo - 9",
      "Narith - 9",
      "Demonkiller - 8",
      "Elvilmandel - 8",
      "Frabos - 7",
      "Zeindra - 6",
      "Umilawen - 5",
      "Kerranna - 5",
      "Isundel - 4",
      "Rakrest - 4",
      "Ismael - 2",
      "Skiteru - 2",
      "Mermereu - 2",
      "Frienta - 2",
      "Granks - 2",
      "Reinke - 1",
      "Watzmann - 1",
      "Poirin - 1",
      "Chalini - 1",
      "Lurtschara - 1",
      "Mima - 1",
    ],
    "Escama de dragón": [
      "Dairu - 34",
      "Amuliu - 34",
      "Sextus - 34",
      "Lepidu - 30",
      "Avalonio - 24",
      "Titaniu - 23",
      "Tellus - 20",
      "Quinto - 16",
      "Poncio - 15",
      "Serviu - 8",
      "Valerio - 6",
      "Dexteru - 5",
      "Antoniu - 4",
      "Constancio - 4",
      "Aurelio - 3",
      "Gaiu - 1",
      "Mandalu - 1",
    ],
    "Cuerno de toro": [
      "Chuck - 21",
      "Leandronimu - 17",
      "Sentarions - 14",
      "Barbekuu - 13",
      "Sphingen - 13",
      "Fernabasts - 12",
      "Kork - 11",
      "Tantus - 11",
      "Shivas - 10",
      "Zimbri - 7",
      "Anchoron - 6",
      "Thorsten - 6",
      "Lucius - 3",
      "Appius - 2",
      "Liloel - 2",
      "Cheggov - 1",
      "Purmann - 1",
    ],
    "Glándula venenosa": [
      "de la Agresión - 18",
      "de la Destrucción - 17",
      "del Golpe Crítico - 16",
      "de la Muerte - 15",
      "de Marte - 12",
    ],
    "Pelaje de Cerbero": [
      "de la Esfinge - 15",
      "de las sombras - 15",
      "de la miseria - 13",
      "de la tortura - 13",
      "de la opresión - 9",
      "de la oscuridad - 8",
      "de la transición - 8",
      "de la agonía - 7",
      "de las ala - 6",
      "del infierno - 5",
      "del calor - 5",
      "de los druidas - 2",
      "del sufrimiento - 1",
    ],
    "Escama de Hidra": [
      "Tiberiu - 42",
      "Arpagiu - 41",
      "Pilato - 41",
      "Minucio - 32",
      "Ambrosio - 25",
      "Porcio - 24",
      "Caesiu - 24",
      "Gratio - 22",
      "Jove - 19",
      "Lete - 18",
      "Mercuriali - 14",
      "Camilo - 13",
      "Sebastiano - 13",
      "Ursu - 12",
      "Asfódelo - 10",
      "Aulo - 10",
      "Gaia - 8",
      "Valentín - 8",
      "Magno - 8",
      "Oraniu - 8",
      "Angelu - 6",
      "Sergiu - 2",
      "Micandrile - 2",
      "Quinta - 2",
      "Aurora - 1",
      "Primulu - 1",
      "Acca - 1",
    ],
    "Pluma de Esfinge": [
      "Mercuriali - 47",
      "Aurora - 37",
      "Aulo - 35",
      "Lete - 33",
      "Porcio 11",
      "Dragonu - 8",
      "Oraniu - 8",
      "Pilato - 6",
      "Quinta - 6",
      "Camilo - 4",
      "Primulu - 4",
      "Minucio - 3",
      "Arpagiu - 3",
      "Gratio - 2",
      "Magno - 2",
      "Micandrile - 2",
      "Jove - 2",
      "Ambrosio - 1",
      "Tiberiu - 1",
      "Sebastiano - 1",
      "Gaia - 1",
      "Acca - 1",
    ],
    "Piel de Tifón": [
      "Camilo - 31",
      "Dragonu - 30",
      "Oraniu - 28",
      "Valentín - 28",
      "Pilato - 21",
      "Primulu - 13",
      "Ursu - 13",
      "Aurora - 9",
      "Sergiu - 8",
      "Aulo - 8",
      "Sebastiano - 6",
      "Gaia - 5",
      "Caesiu - 1",
      "Angelu - 1",
      "Jove - 1",
    ],
  },
  Gemas: {
    Lapislázuli: [
      "Ronaldas - 18",
      "Fustriel - 17",
      "Melanchaeta - 13",
      "Lulu - 8",
      "Evotav - 6",
      "Medoni - 5",
      "Ashitill - 3",
      "Uridos 3",
      "Fitschi - 3",
    ],
    Amatista: [
      "Mateu - 48",
      "Valerio - 47",
      "Marcelo - 36",
      "Serviu - 31",
      "Constancio - 27",
      "Caldus - 24",
      "Giganticus - 23",
      "Gaiu - 22",
      "Dexteru - 21",
      "Antoniu - 18",
      "Amuliu - 18",
      "Lepidu - 15",
      "Titaniu - 14",
      "Belesario - 13",
      "Poncio 13",
      "Tellus 12",
      "Sextus 12",
      "Avalonio - 10",
      "Quinto - 8",
      "Dairus - 1",
    ],
    Ámbar: [
      "del Conocimiento - 17",
      "del Bautismo - 17",
      "de la Concentración - 16",
      "de la Recuperación - 16",
      "de la Superioridad Espiritual - 15",
      "de la Vida - 15",
      "del Relámpago Fantasmal - 14",
      "de la Virtuosidad - 14",
      "de la Inteligencia - 12",
      "de la paz - 12",
      "del regreso - 12",
      "de la Pureza - 11",
      "del Sacramento - 11",
      "de la Pandemia - 10",
      "del Matrimonio - 9",
      "de la Salud - 9",
      "de la firmeza - 7",
      "de la Expansión - 6",
      "de la Resolución - 5",
      "de los Ingreso - 4",
      "de la Ilusión - 4",
      "de la Armonía - 4",
      "de la independencia - 3",
      "del disturbio - 3",
      "de la delicadeza - 3",
      "de la Gracia - 3",
      "del Sol - 2",
      "del Terror 2",
      "de la Victima - 2",
      "de la seguridad - 2",
      "de la Fragmentación - 2",
      "de la magnificencia - 2",
      "de la Masculinidad - 2",
      "de la Corrosión - 1",
      "del Coraje - 1",
      "del Desfile - 1",
      "de la Diligencia - 1",
      "de los Maldito - 1",
      "de la Evasión - 1",
      "del veneno - 1",
      "de la Protección - 1",
      "de la Fragmentación - 1",
    ],
    Aguamarina: [
      "de la Luz - 13",
      "de la Diligencia - 11",
      "del Sol - 11",
      "del Coraje - 11",
      "de la Espátula - 10",
      "de los Ingreso - 9",
      "del Amazona - 9",
      "de la Armonía - 8",
      "del Sufrimiento - 7",
      "de los Muertos Viviente - 5",
      "de la magnificencia - 4",
      "de la Pureza - 4",
      "del Desfile - 4",
      "de la Victima - 4",
      "de la Evasión - 3",
      "de la Ilusión - 3",
      "de la Fragmentación - 2",
      "de la Masculinidad - 1",
      "de los Maldito - 1",
      "del disturbio - 1",
      "de la Gracia - 1",
    ],
    Zafiro: [
      "de la Religiosidad - 12",
      "de la Ceremonia - 11",
      "de la Ordenanza - 10",
      "de la Emasculación - 10",
      "del Luto - 9",
      "de la Consagración - 9",
      "de la Espiritualidad - 9",
      "de los Bendito - 9",
      "de la Curación - 8",
      "de la Curiosidad - 7",
      "de la Normalidad - 7",
      "de la Herida - 7",
      "de la Invisibilidad - 7",
      "de la Liturgia - 6",
      "de la Desesperación - 6",
      "de las Montaña - 5",
      "de la Colina - 5",
      "de la Maldición - 5",
      "de la Lluvia - 4",
      "de las Nube - 4",
      "de la Sangre - 4",
      "de la Luna - 3",
      "de la Locura - 3",
      "del Miedo - 3",
      "de la Presteza - 2",
      "del Orgullo - 2",
      "de la Justicia - 2",
      "del Mar - 2",
      "del Equilibrio - 2",
      "de la Generosidad - 2",
      "de la Carne - 1",
      "de la Demolición - 1",
      "del Honor - 1",
      "de la confusión - 1",
      "del insulto - 1",
      "de la creencia - 1",
      "de la satisfacción - 1",
      "del aprendizaje - 1",
    ],
    Granate: [
      "Marcu - 48",
      "Shivas - 35",
      "Purmann - 32",
      "Liloel - 31",
      "Stoybaer - 29",
      "Anchoron - 20",
      "Jennifer - 13",
      "Opiehnza - 8",
      "Barbekuu - 6",
      "Ichoru - 5",
      "Trafan - 4",
      "Cheggov - 3",
      "Fernabasts - 1",
      "Sentarions - 1",
      "Kork - 1",
      "Lucius - 1",
    ],
    Esmeralda: [
      "Aurelio - 56",
      "Virgilio - 56",
      "Silvano - 54",
      "Spuriu - 52",
      "Mandalu - 52",
      "Caldus - 23",
      "Dexteru - 14",
      "Giganticus - 10",
      "Constancio - 6",
      "Serviu - 4",
      "Manius 4",
      "Avalonio - 4",
      "Belesario - 4",
      "Dairus - 3",
      "Marcelo - 3",
      "Lepidu - 3",
      "Titu - 3",
      "Quinto - 2",
      "Titaniu - 2",
      "Mateus - 2",
      "Sextus - 1",
    ],
    Diamante: [
      "de los Campos Elíseo - 18",
      "de la Rivalidad - 11",
      "de la Ligereza - 9",
      "de la Maldición - 9",
      "de la soledad - 9",
      "del Infierno - 8",
      "de la Tierra - 3",
      "de la Promesa - 3",
    ],
    Jaspe: [
      "del desfiladero - 46",
      "del espíritu - 27",
      "de la tortura - 22",
      "del sueño - 20",
      "de la bestia - 13",
      "de las fatigas - 13",
      "de la miseria - 13",
      "de la tristeza - 10",
      "de los demonio - 10",
      "de la extenuación - 10",
      "de la confianza - 8",
      "de la serpiente - 7",
      "del alma - 7",
      "de la opresión - 6",
      "de las tiniebla - 5",
      "de la decadencia - 5",
      "del peligro - 4",
      "del juez - 4",
      "del sufrimiento - 3",
      "de las profundidade - 2",
      "de la divinidad - 2",
      "del calor - 2",
      "de las ala - 1",
      "de los druidas - 1",
    ],
    Sugilita: [
      "Africanu - 58",
      "Gratia - 47",
      "Angelu - 47",
      "Magno - 44",
      "Caesiu - 44",
      "Jove - 40",
      "Asfódelo - 39",
      "Quinta - 35",
      "Ambrosio - 26",
      "Porcio - 24",
      "Sergiu - 24",
      "Aurora - 22",
      "Valentín - 21",
      "Aulo - 18",
      "Sebastiano - 14",
      "Micandrile - 12",
      "Minucio - 9",
      "Gaia - 8",
      "Acca - 8",
      "Dragonu - 6",
      "Primulu - 5",
      "Lete - 5",
      "Oraniu - 4",
      "Arpagiu - 4",
      "Mercuriali - 3",
      "Gratio - 2",
      "Tiberiu - 2",
      "Ursu - 2",
    ],
  },
  Frascos: {
    "Veneno de escorpión": [
      "del Odio - 15",
      "del misterio - 13",
      "de la Venganza 12",
      "de la Batalla - 12",
      "de la Resolución - 12",
      "del poder - 11",
      "del aprendizaje - 11",
      "de la Fragmentación - 10",
      "del veneno - 10",
      "de la Expansión - 9",
      "del Estímulo - 9",
      "del Amazona - 9",
      "del Asesinato - 9",
      "de la pasión - 7",
      "de la Victima - 7",
      "del Matrimonio - 7",
      "de la Masculinidad - 7",
      "de la Espátula - 6",
      "del disturbio - 6",
      "de la Violencia - 6",
      "del Funámbulo - 5",
      "de la Perdición - 4",
      "del Terror - 4",
      "del Sacramento - 2",
      "de los Ingreso - 1",
      "de la Fragmentación - 1",
      "de la Corrosión - 1",
      "de la delicadeza - 1",
      "de la firmeza - 1",
      "del Homunculus - 1",
      "del Desfile - 1",
    ],
    "Tintura de la resistencia": [
      "Luciu - 27",
      "Sentarions - 24",
      "Tantus - 21",
      "Fernabasts - 21",
      "Kork - 20",
      "Leandronimu - 13",
      "Decimu - 10",
      "Stoybaer - 10",
      "Barbekuu - 10",
      "Anchoron - 9",
      "Appius - 7",
      "Trafan - 6",
      "Ichoru - 5",
      "Opiehnza - 2",
    ],
    Antídoto: [
      "del Homunculu - 16",
      "del Sacrificio 16",
      "de la Ignorancia - 15",
      "del Sentimentalismo - 14",
      "de la Auto-Disciplina - 14",
      "de la Protección - 14",
      "de los Maldito - 12",
      "de los Momento - 12",
      "de la seguridad - 11",
      "de la Retirada 11",
      "del Funámbulo - 8",
      "de la Gracia - 7",
      "de la independencia - 7",
      "del Terror - 6",
      "de la Violencia - 6",
      "de la magnificencia - 6",
      "del disturbio - 5",
      "de la pasión - 5",
      "del Estímulo - 4",
      "de la firmeza - 4",
      "de la Salud - 3",
      "del poder - 1",
    ],
    Adrenalina: [
      "Berecca - 22",
      "Medoni - 22",
      "Fitschi - 20",
      "Heuhoi - 19",
      "Evotav - 10",
      "Umfeta - 9",
      "Uridos - 5",
      "Ashitill - 4",
      "Gidras - 2",
      "Heudoi - 2",
      "Ronalda - 1",
      "Lulu - 1",
      "Melaneo - 1",
    ],
    "Tintura de la inspiración": [
      "de la Ingeniosidad - 23",
      "de la Benevolencia - 21",
      "de la Necedad - 21",
      "de la Consideración - 21",
      "de la Recuperación - 20",
      "de la Resistencia - 20",
      "del Aleluya - 20",
      "de Orión - 19",
      "del Rigor Morti - 19",
      "de la Regeneración - 19",
      "de la Denominación - 15",
      "de la Hipocresía - 13",
      "de la Piedad - 9",
      "de la Vocación - 8",
      "de la Defensa Total - 2",
      "del cielo - 2",
      "de la Muerte - 2",
      "de la Agresión - 2",
      "del Golpe Crítico - 2",
      "de la Herida de Carne - 1",
      "de la Obstrucción - 1",
    ],
    "Poción de la percepción": [
      "Zimbri - 34",
      "Thorsten - 33",
      "Cheggov - 30",
      "Lucius - 12",
      "Sphingen - 12",
      "Appius - 9",
      "Decimu - 7",
      "Ichoru - 2",
      "Opiehnza - 2",
      "Stoybaer - 1",
    ],
    "Esencia de los reflejos": [
      "de la Promesa - 22",
      "de la Tierra - 17",
      "de la Dominancia - 13",
      "de la Marginalidad - 6",
      "de la Ligereza - 5",
      "del Dragón - 4",
      "de los Campos Elíseo - 2",
      "de la plaga - 2",
      "de la Locura - 1",
      "de la Verdad - 1",
      "del Fuego - 1",
    ],
    "Frasco de carisma": [
      "de la plaga - 27",
      "de los Campos Elíseo - 7",
      "de la Rivalidad - 5",
      "de la Tierra - 4",
      "de la Maldición - 4",
      "de la Esperanza - 4",
      "de la Dominancia - 2",
      "del Dragón - 1",
      "de la Promesa - 1",
      "del Fuego - 1",
    ],
    "Agua del olvido": [
      "de los druidas - 38",
      "del fuego infernal - 38",
      "de Tártaro - 33",
      "del terror - 32",
      "del grito - 32",
      "del horror - 31",
      "de la destrucción - 30",
      "de la divinidad - 29",
      "del frío - 28",
      "de la confianza - 27",
      "de la decadencia - 26",
      "de la transición - 25",
      "de la agonía - 22",
      "del juez - 22",
      "del calor - 21",
      "de las profundidade - 20",
      "del infierno - 19",
      "de lo desconocido - 16",
      "del sufrimiento - 16",
      "de la serpiente - 16",
      "del tormento - 15",
      "del fantasma - 15",
      "del Aqueronte - 14",
      "de la Hidra - 13",
      "de la extenuación - 10",
      "del tormento - 9",
      "de las fatigas - 8",
      "de la bestia - 8",
      "de las sombras - 7",
      "de los demonio - 6",
      "de la aparición - 5",
      "de las tiniebla - 4",
      "de la huida - 4",
      "de Mercurio - 3",
      "de la indecisión - 2",
      "de la oscuridad - 2",
      "del desfiladero - 1",
    ],
    "Esencia de alma": [
      "Acca - 73",
      "Gaia - 55",
      "Quinta - 45",
      "Gratia - 19",
      "Arpagiu - 18",
      "Minucio - 15",
      "Camilo - 12",
      "Oraniu - 9",
      "Ambrosio - 8",
      "Tiberiu - 8",
      "Dragonu - 8",
      "Valentín - 6",
      "Asfódelo - 5",
      "Jove - 4",
      "Primulu - 4",
      "Magno - 4",
      "Angelu - 3",
      "Gratio 3",
      "Ursu - 2",
      "Sebastiano 2",
      "Aurora - 1",
    ],
  },
  Runas: {
    "Sello acuático": [
      "Lulu - 9",
      "Ronalda - 7",
      "Fustriel - 7",
      "Melanchaeta - 6",
      "Melaneo - 5",
      "Gidras 5",
      "Zomber - 5",
      "Heudoi - 3",
      "Umfeta - 2",
      "Adendathiel - 1",
    ],
    "Runa protectora": [
      "de la Exactitud - 20",
      "del cielo - 12",
      "de la Enfermedad - 12",
      "de los Espartano - 1",
      "de la Defensa Total - 1",
    ],
    "Grabado terrestre": [
      "de la Prisa - 10",
      "de la Nostalgia - 7",
      "de la Rapidez - 7",
      "del Dolor - 6",
      "de la Voluntad - 5",
      "de la Distracción - 5",
      "de la Lluvia - 4",
      "de la Presteza - 4",
      "de la Locura - 4",
      "de la Sangre - 4",
      "del obstáculo - 3",
      "de la Habilidad - 3",
      "de la Luna - 3",
      "del Miedo - 3",
      "del Mar - 2",
      "de la vacilación - 2",
      "del Equilibrio - 2",
      "de la Extirpación - 2",
      "del Bosque - 1",
      "del Conflicto - 1",
      "de la Fusión - 1",
    ],
    "Tótem curativo": [
      "del Amor - 30",
      "de la Verdad - 27",
      "de la soledad - 24",
      "de la Locura - 23",
      "de la Marginalidad - 7",
      "de la plaga - 6",
      "de la Esperanza - 4",
      "de los Campos Elíseo - 4",
      "de la Maldición - 3",
      "de la Rivalidad - 2",
      "del Infierno - 2",
      "de la Fuerza - 1",
      "de la Promesa - 1",
      "de la Dominancia - 1",
      "de la Tierra - 1",
    ],
    "Talismán de poder": [
      "de la malicia - 20",
      "de la Antigüedad - 13",
      "de la Vocación - 11",
      "de la Piedad - 9",
      "de la Enfermedad - 9",
      "de la Presión - 9",
      "de la Libertad - 9",
      "de Marte - 7",
      "de la Hipocresía - 6",
      "de la Denominación - 3",
      "de la Destrucción - 2",
      "de la Prevención - 2",
      "de los Espartano - 2",
      "de la Obstrucción - 1",
      "de la Defensa Total - 1",
      "de la Herida de Carne - 1",
      "de la Muerte - 1",
      "de la Regeneración - 1",
      "de la Agresión - 1",
      "del Golpe Crítico - 1",
    ],
    "Piedra de la suerte": [
      "del silencio - 12",
      "de la Fragmentación - 11",
      "de los Muertos Viviente - 4",
      "de la delicadeza - 4",
      "de la pasión - 3",
      "de la Ilusión - 2",
      "de la Masculinidad - 2",
      "de la independencia - 1",
      "del veneno - 1",
      "del aprendizaje - 1",
      "del Asesinato - 1",
    ],
    Pedernal: [
      "Táliths - 22",
      "Orleld - 21",
      "Adendathiel - 20",
      "Uridos - 15",
      "Ashitill - 13",
      "Heuhoi - 10",
      "Evotav - 9",
      "Lulu - 5",
      "Melaneo - 3",
      "Zomber - 3",
      "Berecca - 1",
      "Fitschi - 1",
      "Umfeta - 1",
      "Ronalda - 1",
      "Gidras - 1",
      "Fustriel - 1",
      "Melanchaeta - 1",
    ],
    "Runa de la tormenta": [
      "Umbros - 40",
      "Chucks - 23",
      "Xenphlames - 21",
      "Opiehnza - 18",
      "Appius - 7",
      "Sentarions - 7",
      "Trafan - 6",
      "Tantus - 4",
      "Lucius - 4",
      "Kork - 3",
      "Fernabasts - 1",
    ],
    "Runa de las sombras": [
      "de las ala - 27",
      "de la noche - 27",
      "del peligro - 26",
      "de la indecisión - 23",
      "del tormento - 20",
      "de la piedra - 17",
      "de la tristeza - 13",
      "del sufrimiento - 12",
      "del sueño - 11",
      "del juez - 6",
      "de la Esfinge - 4",
      "de la decadencia - 4",
      "de los druidas - 4",
      "del horror - 3",
      "de la oscuridad - 2",
    ],
  },
  Minerales: {
    Cristal: [
      "Maniu - 42",
      "Gaiu - 31",
      "Belesario - 30",
      "Antoniu - 30",
      "Titu - 29",
      "Quinto - 25",
      "Poncio - 22",
      "Tellus - 19",
      "Marcelo - 17",
      "Titaniu - 17",
      "Serviu - 8",
      "Dexteru - 6",
      "Valerio - 6",
      "Constancio - 4",
      "Amuliu - 2",
    ],
    Bronce: [
      "de la Revancha - 22",
      "del Dragón - 20",
      "de la Esperanza - 18",
      "del Infierno - 14",
      "de la Rivalidad - 11",
      "de la Maldición - 11",
      "de la Marginalidad - 7",
      "de la Ligereza - 6",
      "de la Tierra - 4",
      "de la Dominancia - 4",
      "de la Fuerza - 3",
      "del Fuego - 3",
      "de la Promesa - 2",
    ],
    Obsidiana: [
      "Avalonio - 13",
      "Dairus - 12",
      "Constancio - 12",
      "Caldus - 11",
      "Giganticus - 11",
      "Belesario - 8",
      "Titu - 8",
      "Poncio - 7",
      "Lepidu - 5",
      "Quinto - 4",
      "Sextus - 4",
      "Tellus - 1",
    ],
    Plata: [
      "de la Corrosión - 12",
      "de la Evasión - 10",
      "del Sufrimiento - 9",
      "del Desfile - 8",
      "de la Perdición - 8",
      "de la delicadeza - 5",
      "de los Muertos Viviente - 5",
      "de la Ilusión - 3",
      "de la Pandemia - 3",
      "de la Espátula - 2",
      "de la Fragmentación - 2",
      "del Asesinato - 1",
      "de la Retirada - 1",
      "de la independencia - 1",
      "de la Expansión - 1",
    ],
    Azufre: [
      "Ichoru - 35",
      "Decimu - 32",
      "Jennifer - 29",
      "Trafan - 19",
      "Appius 13",
      "Opiehnza - 12",
      "Xenphlames - 12",
      "Tantus - 12",
      "Anchoron - 12",
      "Leandronimu - 11",
      "Barbekuu - 9",
      "Sphingen - 9",
      "Thorsten - 4",
      "Zimbri - 4",
      "Fernabasts 4",
      "Cheggov - 3",
      "Purmann - 3",
      "Lucius - 2",
      "Stoybaer - 1",
    ],
    "Mena de oro": [
      "Titu - 12",
      "Giganticus - 10",
      "Amuliu - 8",
      "Caldus - 7",
      "Avalonio - 7",
      "Dexteru - 6",
      "Constancio - 4",
      "Manius - 4",
      "Tellus - 3",
      "Antoniu - 3",
      "Lepidu - 3",
      "Titaniu - 2",
      "Poncio - 1",
      "Sextus - 1",
    ],
    Cuarzo: [
      "de la Fuerza - 23",
      "del Fuego - 19",
      "de la Marginalidad - 7",
      "de la Ligereza - 6",
      "de la Dominancia - 6",
      "del Dragón - 4",
      "de la Revancha - 2",
      "de la Promesa - 1",
    ],
    Platino: [
      "de la Herida de Carne - 19",
      "de la Obstrucción - 16",
      "de los Espartano - 14",
      "de la Defensa Total - 14",
      "de la Prevención - 13",
      "de la Antigüedad - 3",
      "de la Presión - 1",
      "de la Libertad - 1",
    ],
    Almandino: [
      "Escribonio - 70",
      "Micandrile - 45",
      "Gratio - 37",
      "Primulu - 37",
      "Ursu - 33",
      "Sergius - 31",
      "Sebastiano - 24",
      "Africanu - 12",
      "Porcio - 11",
      "Angelus - 10",
      "Camilo - 8",
      "Dragonus - 8",
      "Tiberius - 8",
      "Asfódelo - 6",
      "Magno - 6",
      "Minucio - 5",
      "Oraniu - 5",
      "Gratias - 3",
      "Ambrosio - 2",
      "Lete - 2",
    ],
    Cuprita: [
      "del abismo - 34",
      "de Mercurio - 27",
      "de la piedra - 16",
      "de la huida - 11",
      "del Aqueronte - 10",
      "de los demonio - 9",
      "de la confianza - 6",
      "del espíritu - 5",
      "de la divinidad - 4",
      "de la oscuridad - 4",
      "del sueño - 3",
      "de la agonía - 2",
      "de las profundidades - 1",
    ],
    "Piedra infernal": [
      "de Cerbero - 33",
      "de la aparición - 29",
      "del alma - 26",
      "del tormento 25",
      "de las tinieblas - 22",
      "de la opresión - 20",
      "de la Hidra - 20",
      "de la huida - 19",
      "de lo desconocido - 17",
      "del fantasma - 17",
      "de la Esfinge - 16",
      "de la oscuridad - 15",
      "de la extenuación - 14",
      "de las fatigas - 13",
      "de las profundidade - 11",
      "de las sombras - 11",
      "de la bestia - 11",
      "del infierno - 10",
      "de la serpiente - 10",
      "de la tristeza - 8",
      "del Aqueronte - 8",
      "de los demonio - 8",
      "del peligro - 5",
      "de la indecisión - 5",
      "de la noche - 5",
      "de la destrucción - 4",
      "de la miseria - 4",
      "de Mercurio - 3",
      "del calor - 3",
      "de la agonía - 3",
      "del terror - 2",
      "del frío - 2",
      "del sufrimiento - 1",
      "del juez - 1",
    ],
  },
};
